#!/usr/bin/env bash

# set -x # Only used for debugging...
set -euo pipefail

# Define color codes
COLOR_RESET='\033[0m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_CYAN='\033[0;36m'

die() {
  printf "[${COLOR_RED}ERROR${COLOR_RESET}]: %s\n" "$1" >&2
  exit 1
}

has() {
  command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"
}

# vim:sw=2:ts=2:et:
