#!/usr/bin/env bash

# set -x
set -euo pipefail

NOTIFICATION_ID=1001

main() {
  while [ $# -gt 0 ]; do
    ACTION=$1

    if [ -z "$ACTION" ]; then
      echo "Usage: $(basename "$0") <up|down>"
      exit 1
    fi

    case "$ACTION" in
      up)
        brightnessctl set 10%+
        ;;
      down)
        brightnessctl set 10%-
        ;;
      *)
        echo "Invalid action: $ACTION"
        exit 1
        ;;
    esac

    BRIGHTNESS=$(brightnessctl info | awk '/Current brightness:/ {print $4}' | sed 's/(\(.*\)%)/\1/')

    SUMMARY="Brightness: $BRIGHTNESS%"
    BODY=""

    notify-send -u normal -a 'Brightness' "$SUMMARY" "$BODY" -r "$NOTIFICATION_ID"
    # notify-send -u normal -a 'Brightness' "$SUMMARY" "$BODY" -r "$NOTIFICATION_ID" -h "int:value:$BRIGHTNESS"

    exit 0
  done

  if [ $# -ne 1 ]; then
    echo "Usage: $(basename "$0") <up|down|mute>"
    exit 1
  fi
}

main "$@"

# vim:sw=2:ts=2:et:
