#!/usr/bin/env bash

# set -x # WARN: Only used for debugging...
set -euo pipefail

STATE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/caffeine_state"

command -v xset >/dev/null 2>&1 || {
  echo "xset not found" >&2
  exit 1
}
command -v dunstify >/dev/null 2>&1 || {
  echo "dunstify not found" >&2
  exit 1
}

status=$(xset -q 2>/dev/null | sed -n 's/.*DPMS is \(Enabled\|Disabled\).*/\1/p')

if [ "$status" = 'Enabled' ]; then
  xset s off -dpms &&
    dunstify -i caffeine-on 'Caffeine' "Display can't sleep now" &&
    echo "off" >"$STATE_FILE"
else
  xset s on +dpms &&
    dunstify -i caffeine-off 'Caffeine' "Display can sleep now" &&
    echo "on" >"$STATE_FILE"
fi

# vim:ft=sh:sw=2:ts=2:et:
