#!/usr/bin/env bash

dmenu-picker() {
  local prompt="$1"
  shift
  local options=("$@")

  printf "%s\n" "${options[@]}" |
    dmenu -i -l 10 -p "$prompt" \
      -nb '#000000' -nf '#FFFFFF' \
      -sb '#FFFFFF' -sf '#000000' \
      -fn 'Maple Mono NF:regular:pixelsize=14'
}

dmenu-picker "$@"
