#!/usr/bin/env bash

tmux_sessions=$(tmux list-sessions -F "#S")

chosen_session=$(dmenu-picker 'Sessions' "${tmux_sessions[@]}")

if [ -z "$chosen_session" ]; then
  echo "Session selection canceled."
  exit 0
fi

$TERM -e tmux attach -t "$chosen_session"
