#!/usr/bin/env bash

set -x # Uncomment for debugging...
set -e
set -u
set -o pipefail

main() {
  local prompt="$1"
  shift

  if [ $# -gt 0 ]; then
    # options passed as arguments
    printf "%s\n" "$@" |
      dmenu -i -l 10 -p "$prompt" \
        -nb '#000000' -nf '#FFFFFF' \
        -sb '#FFFFFF' -sf '#000000' \
        -fn 'Recursive Sans Casual Static:regular:pixelsize=14'
  else
    # no arguments → read from stdin
    dmenu -i -l 10 -p "$prompt" \
      -nb '#000000' -nf '#FFFFFF' \
      -sb '#FFFFFF' -sf '#000000' \
      -fn 'Recursive Sans Casual Static:regular:pixelsize=14'
  fi
}

main "$@"
