#!/usr/bin/env bash

file="$(mpc listall | dmenu -i -l 5 -p 'Next On Queue' \
	-nb '#000000' -nf '#FFFFFF' \
	-sb '#FFFFFF' -sf '#000000' \
	-fn 'Maple Mono NF:regular:pixelsize=12.5')" || exit 0

mpc insert "$file" && mpc next >/dev/null
