#!/usr/bin/env bash

export DISPLAY="${DISPLAY:-:0}"

OUTDIR="${2:-$HOME/Pictures/Screenshots}"

mkdir -p "$OUTDIR"

FILE="$OUTDIR/$(date +%Y%m%d_%H%M%S).png"

TMP=$(mktemp --suffix=.png)

trap 'rm -f "$TMP"' EXIT

show_help() {
  program=$(basename "$0")
  echo "Usage: $program [color|full|window] [output_dir]"
}

post() {
  xclip -selection clipboard -t image/png -i "$FILE" && notify-send -i "$FILE" "Captured" "$(basename "$FILE")"
  command -v imgcliphist && imgcliphist add
}

colorpicker() {
  if command -v slop &>/dev/null; then
    import -window root -crop "$(slop --tolerance=0 || exit 1)" "$TMP"
  else
    import "$TMP"
  fi
  hex=$(magick "$TMP" -scale 1x1\! -format "#%[hex:p{0,0}]" info: 2>/dev/null || echo "#??????")
  echo -n "$hex" | xclip -selection clipboard -i && notify-send -i "$TMP" "Color" "$hex"
}

capture_full() {
  import -window root "$FILE" && post
}

capture_window() {
  import -window "$(xdotool getwindowfocus -f)" "$FILE" && post
}

capture_selection() {
  import "$FILE" && post
}

capture_main() {
  capture_mode=$(dmenu-picker "Capture" "Color" "Monitor" "Window" "Region")

  case "$capture_mode" in
    [cC]olor) colorpicker ;;
    [mM]onitor) capture_full ;;
    [wW]indow) capture_window ;;
    [rR]egion) capture_selection ;;
    *) show_help ;;
  esac
}

capture_main "$@"

# vim:sw=2:ts=2:et:
