#!/usr/bin/env bash

# set -x # WARN: Only used for debugging...
set -euo pipefail

NOTIFICATION_ID=1010

COLORS=(cockatoo nano everforest macro gruvbox-material solarized sonokai onedark)

main() {
  COLOR=$(dmenu-picker 'Color' cockatoo nano everforest macro gruvbox-material solarized sonokai onedark)

  if printf '%s\0' "${COLORS[@]}" | grep -F -x -z -- "$COLOR"; then
    notify-send -r "$NOTIFICATION_ID" -a 'Colors' 'Colors' "Using '$COLOR'"
  else
    notify-send -r "$NOTIFICATION_ID" -a 'Colors' 'Colors' 'O.o'
    exit 1
  fi

  setcolor "$COLOR"
}

main "$@"

# vim:sw=2:ts=2:et:
