#!/usr/bin/env bash

main() {
  chosen=$(dmenu-picker 'SYSTEM ::' Shutdown Reboot Lock Suspend Logout Kill)

  if [ -n "$chosen" ]; then
    case "$chosen" in
      Shutdown)
        systemctl poweroff
        ;;
      Reboot)
        systemctl reboot
        ;;
      Lock)
        playerctl play-pause
        mpc -q pause
        amixer set Master mute
        xset s activate
        ;;
      Suspend)
        playerctl play-pause
        mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
      Logout)
        pkill -KILL -u "$USER"
        ;;
      Kill)
        ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu-picker 'KILL ::' | awk '{print $1}' | xargs -r kill
        ;;
      *)
        exit 1
        ;;
    esac
  fi
}

main "$@"

# vim:sw=2:ts=2:et:
