#!/usr/bin/env bash

set -x # Uncomment for debugging...
set -e
set -u
set -o pipefail

OPTIONS=$(mpc listall)

SONG=$(dmenu-picker 'Pick a Song' "${OPTIONS[@]}")

if [[ -z "$SONG" ]]; then
  exit 1
else
  mpc insert "$SONG" && mpc next
fi

# vim:sw=2:ts=2:et:
