#!/usr/bin/env bash

set -x # WARN: Only used for debugging...
set -euo pipefail

COLOR_RESET='\033[0m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_CYAN='\033[0;36m'

COLORS=(cockatoo nano everforest macro gruvbox-material solarized sonokai onedark)

main() {
  COLOR=$(dmenu-picker 'Color' cockatoo nano everforest macro gruvbox-material solarized sonokai onedark)

  if printf '%s\0' "${COLORS[@]}" | grep -F -x -z -- "$COLOR"; then
    notify-send 'Colors' "Using '$COLOR'"
  else
    notify-send 'Colors' 'O.o'
    exit 1
  fi

  setcolor "$COLOR"
}

main "$@"

# vim:sw=2:ts=2:et:
