#!/usr/bin/env bash

NOTIFYCMD=$(which dunstify 2>/dev/null || which notify-send 2>/dev/null)

usage() {
  program=$(basename "$0")
  echo "$program - image manipulation utility"
  echo ""
  echo "Usage: $program <operation> [files...]"
  echo ""
  echo "Operations:"
  echo "  png                Convert images to PNG format."
  echo "  jpg                Convert images to JPG format."
  echo "  bb                 Add a black border (50px) to images."
  echo "  wb                 Add a white border (50px) to images."
  echo "  cb                 Add a border by cropping/drawing a rectangle."
  echo "  bw                 Convert images to black and white."
  echo "  tr                 Attempt to remove image background."
  echo "  tc                 Attempt to remove background and copy to clipboard."
  echo "  sc                 Scale images to 50%."
  echo "  fh                 Horizontally flip images."
  echo "  fv                 Vertically flip images."
  echo ""
  echo "Example:"
  echo "  $program bb *.jpg"
  echo "  $program tr image.png"
  exit 0
}

into_png() {
  for IMG in "$@"; do
    mogrify -format png "$IMG" && $NOTIFYCMD "Converted $IMG to png."
  done
}

into_jpg() {
  for IMG in "$@"; do
    mogrify -format jpg "$IMG" && $NOTIFYCMD "Converted $IMG to jpg."
  done
}

black_border() {
  for IMG in "$@"; do
    magick "$IMG" -bordercolor black -border 50x50 "$IMG.border" && $NOTIFYCMD "Added black border to $IMG."
  done
}

white_border() {
  for IMG in "$@"; do
    magick "$IMG" -bordercolor white -border 50x50 "$IMG.border" && $NOTIFYCMD "Added white border to $IMG."
  done
}

crop_border() {
  for IMG in "$@"; do
    magick "$IMG" -fill black -stroke none -draw "rectangle 0,0 %[fx:w],%[fx:h*0.05] rectangle 0,0 %[fx:w*0.05],%[fx:h] rectangle %[fx:w-w*0.05],0 %[fx:w],%[fx:h] rectangle 0,%[fx:h-h*0.05] %[fx:w],%[fx:h]" "$IMG.cropborder" && $NOTIFYCMD "Cropped+bordered $IMG."
  done
}

black_white() {
  for IMG in "$@"; do
    magick "$IMG" -colorspace Gray "$IMG.bw" && $NOTIFYCMD "B&W'd $IMG."
  done
}

transparency() {
  for IMG in "$@"; do
    magick "$IMG" -alpha off -fuzz 10% -fill none -draw "alpha 0,0 floodfill" \( +clone -alpha extract -blur 0x2 -level 50x100% \) -alpha off -compose copy_opacity -composite "$IMG.trnsprnt" && $NOTIFYCMD "Removed background from $IMG."
  done
}

transparencyrecopy() {
  for IMG in "$@"; do
    magick "$IMG" -alpha off -fuzz 10% -fill none -draw "alpha 0,0 floodfill" \( +clone -alpha extract -blur 0x2 -level 50x100% \) -alpha off -compose copy_opacity -composite "$IMG.trnsprnt"
    xclip -i -selection clipboard -t image/png "$IMG.trnsprnt"
    $NOTIFYCMD -i "$IMG.trnsprnt" "$IMG background removed and recopied "
  done
}

scale() {
  for IMG in "$@"; do
    mogrify "$IMG" -scale 50% "$IMG".scale && $NOTIFYCMD "Scaled $IMG to 50%."
  done
}

horizontal_flip() {
  for IMG in "$@"; do
    magick "$IMG" -flop "$IMG".flip && $NOTIFYCMD "Horizontally flipped $IMG."
  done
}

vertical_flip() {
  for IMG in "$@"; do
    magick "$IMG" -flip "$IMG".vflip && $NOTIFYCMD "Vertically flipped $IMG."
  done
}

case $1 in
  png)
    shift
    into_png "$@"
    ;;
  jpg)
    shift
    into_jpg "$@"
    ;;
  bb)
    shift
    black_border "$@"
    ;;
  wb)
    shift
    white_border "$@"
    ;;
  cb)
    shift
    crop_border "$@"
    ;;
  bw)
    shift
    black_white "$@"
    ;;
  tr)
    shift
    transparency "$@"
    ;;
  tc)
    shift
    transparencyrecopy "$@"
    ;;
  sc)
    shift
    scale "$@"
    ;;
  fh)
    shift
    horizontal_flip "$@"
    ;;
  fv)
    shift
    vertical_flip "$@"
    ;;
  *) usage ;;
esac

# vim:sw=2:ts=2:et:
