#!/usr/bin/env bash

# set -x # WARN: Only used for debugging...
set -e
set -u
set -o pipefail

RUN_DIR=$(dirname "$(nvim --clean --headless +"lua io.write(vim.fn.stdpath('run'))" +qa!)")
APPNAME=${NVIM_APPNAME:-nvim}

fd_cmd=$(has fd && echo fd || echo fdfind)

if has "$fd_cmd"; then
  "$fd_cmd" -a --base-directory "$RUN_DIR" -t s -g "$APPNAME.*.0"
else
  find "$RUN_DIR" -type s -name "$APPNAME.*.0"
fi

# vim:ft=sh:ts=2:sw=2:et:
