#!/usr/bin/env bash

# Open a shell in a temporary directory.

DIR=/tmp/$$.room

mkdir -p "$DIR"

trap 'rm -rf -- "${DIR:-?}"' EXIT INT TERM HUP

cd "$DIR" || exit 0

echo -n "$DIR" | xclip -selection clipboard

(${SHELL:-/bin/sh})
