#!/usr/bin/env bash

build() {
    case "$1" in
    *.c) gcc "$1" -o "$2" ;;
    *.cpp|*.cc|*.cxx) g++ "$1" -o "$2" ;;
    *.rs) rustc "$1" -o "$2" ;;
    *.go) go build -o "$2" "$1" ;;
    esac
}

exec() {
    "$1"
}

main() {
    local src=$(fullpath "$1")
    local executable=$(echo "$src" | sed -E 's/\.(c|cpp|cc|cxx|rs|go)$/.run/')
    if [[ "$src" == "$executable" ]]; then
        echo >&2 "run: error: file name cannot be the same as the run file name"
        exit 1
    fi

    build "$src" "$executable"
    if [[ ! -f "$executable" ]]; then
        echo >&2 "run: error: cannot remove run file because it does not exist"
        exit 1
    fi

    exec "$executable"
    rm "$executable"
}

main "$1"
