#!/usr/bin/env bash

# set -x # Uncomment for debugging...
set -e
set -u
set -o pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

DEFAULT_BG='dark'

usage() {
  echo "Usage: $(basename "$0") [light|dark]"
  exit
}

update_fish() {
  ( 
    cd "$CONFIG_HOME/fish/themes" || return
    theme_path="Current.theme"
    if [ -z "$1" ]; then
      case "$DEFAULT_BG" in
        dark) [ -e "Dark.theme" ] && ln -s "Dark.theme" "$theme_path" 2>/dev/null ;;
        light) [ -e "Light.theme" ] && ln -s "Light.theme" "$theme_path" 2>/dev/null ;;
      esac
    else
      case "$1" in
        dark) [ -e "Dark.theme" ] && ln -sf "Dark.theme" "$theme_path" ;;
        light) [ -e "Light.theme" ] && ln -sf "Light.theme" "$theme_path" ;;
      esac
    fi
    has fish &&
      fish -c 'set -U __fish_reload_theme (head -c 16 /dev/urandom | sha256sum)'
  )
}

update_nvim() {
  if [ -z "$1" ] || ! has nvim; then
    return 1
  fi

  if ! has nvim-socks; then
    echo "Error: script 'nvim-socks' not found, skip setting backgroud for nvim" >&2
    return 1
  fi

  nvim_clients=""

  for sock in $(timeout 1 nvim-socks); do
    # Notice: Don't use `--remote-send "<Cmd>...<CR>"` to send the command
    # here because of nvim's bug where the string following `<Cmd>` will be
    # interpreted as normal keys (not as part of a command) if nvim is in
    # operator-pending/replace mode. This makes nvim unexpectedly insert
    # the command string "f &bg ..." to the buffer, see:
    # https://github.com/neovim/neovim/issues/31238
    #
    # Sometimes nvim leaves unused sockets on system. Sending remote expr
    # to these sockets will freeze our nvim client, so use timeout 1 and
    # kill the nvim client if it does not exit within the threshold.
    timeout 1 nvim --clean --headless --server "$sock" \
      --remote-expr "execute(\"if &bg !=# '$1' && &tgc \
      | let g:script_set_bg=1 | set bg=$1 | unlet g:script_set_bg \
      | endif\")" \
      +qa! >/dev/null 2>&1 &

    nvim_clients="$nvim_clients $!"
  done

  if ! has jq; then
    echo "Warning: 'jq' not executable, skip writing to nvim's colorscheme file" >&2
  else
    colors_json="$STATE_HOME/nvim/colors.json"
    if [ ! -e "$colors_json" ]; then
      touch "$colors_json"
    fi
    bg=$(jq -r '.bg' "$colors_json")
    if [ "$bg" != "$1" ]; then
      jq --arg bg "$1" '.bg = $bg' \
        "$colors_json" >"$colors_json.tmp"
      mv "$colors_json.tmp" "$colors_json"
    fi
  fi

  if [ -n "$nvim_clients" ]; then
    # shellcheck disable=SC2086
    wait $nvim_clients
  fi
}

update_ghostty() {
  ( 
    cd "$CONFIG_HOME/ghostty/themes" || return
    theme_path="current"
    if [ -z "$1" ]; then
      [ -e "$DEFAULT_BG" ] &&
        ln -s "$DEFAULT_BG" "$theme_path" 2>/dev/null
    else
      [ -e "$1" ] &&
        ln -sf "$1" "$theme_path"
    fi

    kill -USR2 "$(pgrep ghostty)"
  )
}

update_highlight() {
  ( 
    cd "$HOME/.highlight" || return
    themes_dir="themes"
    theme_path="highlight.theme"
    if [ -z "$1" ]; then
      [ -e "$themes_dir/$DEFAULT_BG.theme" ] &&
        ln -s "$themes_dir/$DEFAULT_BG.theme" "$theme_path" 2>/dev/null
    else
      [ -e "$themes_dir/$1.theme" ] &&
        ln -sf "$themes_dir/$1.theme" "$theme_path"
    fi
  )
}

main() {
  lockfile="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/setbg.lock"

  exec 9>"$lockfile"

  if ! flock -n 9; then
    echo "Waiting for existing instance (lock: '$lockfile')" >&2
    flock 9
  fi

  bg=''

  for arg in "$@"; do
    case "$arg" in
      light | dark)
        bg="$arg"
        shift
        ;;
      *)
        usage
        ;;
    esac
  done

  trap 'kill $(jobs -p) 2>/dev/null; wait' EXIT INT TERM HUP

  update_fish "$bg" &
  update_nvim "$bg" &
  update_ghostty "$bg" &
  update_highlight "$bg" &

  wait
}

main "$@"

# vim:ft=sh:ts=2:sw=2:et:
