#!/usr/bin/env bash

# set -x # Uncomment for debugging...
set -e
set -u
set -o pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

DEFAULT_COLOR='macro'

usage() {
  echo "Usage: $(basename "$0") [<colorscheme>]"
  exit
}

format_color() {
  if ! has awk || ! has sed; then
    return 1
  fi

  theme_name=$(echo "$1" |
    sed 's/-/ /g' |
    awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')

  echo "$theme_name"
}

update_fish() {
  ( 
    cd "$CONFIG_HOME/fish/themes" || return
    dark_theme_path="Dark.theme"
    light_theme_path="Light.theme"
    default_theme_name=$(format_color "$DEFAULT_COLOR")
    if [ -z "$1" ]; then
      [ -e "${default_theme_name} Dark.theme" ] && ln -s "${default_theme_name} Dark.theme" "$dark_theme_path" 2>/dev/null
      [ -e "${default_theme_name} Light.theme" ] && ln -s "${default_theme_name} Light.theme" "$light_theme_path" 2>/dev/null
    else
      theme_name=$(format_color "$1")
      [ -e "${theme_name} Dark.theme" ] && ln -sf "${theme_name} Dark.theme" "$dark_theme_path"
      [ -e "${theme_name} Light.theme" ] && ln -sf "${theme_name} Light.theme" "$light_theme_path"
    fi
    has fish &&
      fish -c 'set -U __fish_reload_theme (head -c 16 /dev/urandom | sha256sum)'
  )
}

update_nvim() {
  if [ -z "$1" ] || ! has nvim; then
    return 1
  fi

  if ! has nvim-socks; then
    echo "Error: script 'nvim-socks' not found, skip setting colors for nvim" >&2
    return 1
  fi

  nvim_clients=""

  for sock in $(timeout 1 nvim-socks); do
    # Notice: Don't use `--remote-send "<Cmd>...<CR>"` to send the command
    # here because of nvim's bug where the string following `<Cmd>` will be
    # interpreted as normal keys (not as part of a command) if nvim is in
    # operator-pending/replace mode. This makes nvim unexpectedly insert
    # the command string "f &bg ..." to the buffer, see:
    # https://github.com/neovim/neovim/issues/31238
    #
    # Sometimes nvim leaves unused sockets on system. Sending remote expr
    # to these sockets will freeze our nvim client, so use timeout 1 and
    # kill the nvim client if it does not exit within the threshold.
    timeout 1 nvim --clean --headless --server "$sock" \
      --remote-expr "execute(\"if get(g:, 'colors_name', '') !=# '$1' | \
      let g:script_set_colors=1 | silent! colors $1 | \
      unlet g:script_set_colors | endif\")" \
      +qa! >/dev/null 2>&1 &

    nvim_clients="$nvim_clients $!"
  done

  if ! has jq; then
    echo "Warning: 'jq' not executable, skip writing to nvim's colorscheme file" >&2
  else
    colors_json="$STATE_HOME/nvim/colors.json"
    if [ ! -e "$colors_json" ]; then
      touch "$colors_json"
    fi
    colors_name=$(jq -r '.colors_name' "$colors_json")
    if [ "$colors_name" != "$1" ]; then
      jq --arg colors_name "$1" '.colors_name = $colors_name' \
        "$colors_json" >"$colors_json.tmp"
      mv "$colors_json.tmp" "$colors_json"
    fi
  fi

  if [ -n "$nvim_clients" ]; then
    # shellcheck disable=SC2086
    wait $nvim_clients
  fi
}

update_ghostty() {
  ( 
    cd "$CONFIG_HOME/ghostty/themes" || return
    dark_theme_path="dark"
    light_theme_path="light"
    if [ -z "$1" ]; then
      [ -e "$DEFAULT_COLOR-dark" ] && ln -s "$DEFAULT_COLOR-dark" "$dark_theme_path" 2>/dev/null
      [ -e "$DEFAULT_COLOR-light" ] && ln -s "$DEFAULT_COLOR-light" "$light_theme_path" 2>/dev/null
    else
      [ -e "$1-dark" ] && ln -sf "$1-dark" "$dark_theme_path"
      [ -e "$1-light" ] && ln -sf "$1-light" "$light_theme_path"
    fi

    kill -USR2 "$(pgrep ghostty)"
  )
}

update_highlight() {
  ( 
    cd "$HOME/.highlight/themes" || return
    dark_theme_path="dark.theme"
    light_theme_path="light.theme"
    if [ -z "$1" ]; then
      [ -e "$DEFAULT_COLOR-dark.theme" ] && ln -s "$DEFAULT_COLOR-dark.theme" "$dark_theme_path" 2>/dev/null
      [ -e "$DEFAULT_COLOR-light.theme" ] && ln -s "$DEFAULT_COLOR-light.theme" "$light_theme_path" 2>/dev/null
    else
      [ -e "$1-dark.theme" ] && ln -sf "$1-dark.theme" "$dark_theme_path"
      [ -e "$1-light.theme" ] && ln -sf "$1-light.theme" "$light_theme_path"
    fi
  )
}

main() {
  lockfile="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/setcolor.lock"

  exec 9>"$lockfile"

  if ! flock -n 9; then
    echo "Waiting for existing instance (lock: '$lockfile')" >&2
    flock 9
  fi

  color=''

  for arg in "$@"; do
    case "$arg" in
      -h | --help)
        usage
        ;;
      *)
        color="$arg"
        shift
        ;;
    esac
  done

  trap 'kill $(jobs -p) 2>/dev/null; wait' EXIT INT TERM HUP

  update_fish "$color" &
  update_nvim "$color" &
  update_ghostty "$color" &
  update_highlight "$color" &

  wait
}

main "$@"

# vim:ft=sh:ts=2:sw=2:et:
