#!/usr/bin/env bash
# vim:ft=sh:et:ts=4:sw=4:sts=4:

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

switch_alacritty() {
    (
        ALACRITTY_CONFIG="$CONFIG_HOME/alacritty/local.toml"

        if [ ! -f "$ALACRITTY_CONFIG" ]; then
            echo "[font.normal]" > "$ALACRITTY_CONFIG"
            echo "family = '$FONT'" >> "$ALACRITTY_CONFIG"
        else
            sed -i "s|^\([[:space:]]*\)family = .*|\1family = '$FONT'|" "$ALACRITTY_CONFIG"
        fi

        touch "$CONFIG_HOME/alacritty/alacritty.toml"
    )
}

switch_ghostty() {
    (
        GHOSTTY_CONFIG="$CONFIG_HOME/ghostty/config.local"

        if [ ! -f "$GHOSTTY_CONFIG" ]; then
            echo "font-family = \"$FONT\"" > "$GHOSTTY_CONFIG"
        else
            sed -i "s|^font-family = .*|font-family = \"$FONT\"|" "$GHOSTTY_CONFIG"
        fi

        kill -USR2 "$(pgrep ghostty)"
    )
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <font_name>"
        echo "Available fonts: APL385 Unicode, APL386 Unicode, BQN386 Unicode, Comic Mono, mononoki"
        exit 1
    fi

    FONT="$1"

    AVAILABLE_FONTS=("APL385 Unicode" "APL386 Unicode" "BQN386 Unicode" "Comic Mono" "mononoki")

    VALID=false

    for avail in "${AVAILABLE_FONTS[@]}"; do
        if [ "$FONT" = "$avail" ]; then
            VALID=true
            break
        fi
    done

    if [ "$VALID" = false ]; then
        echo "Invalid font. Available fonts: ${AVAILABLE_FONTS[*]}"
        exit 1
    fi

    switch_alacritty
    switch_ghostty

    echo "Font switched to $FONT"
}

main "$@"
