#!/usr/bin/env bash
# vim:ft=sh:et:ts=4:sw=4:sts=4:

CONFIGURATIONS="${XDG_CONFIG_HOME:-$HOME/.config}"

FONT_IN_USE=$(sed 's/font-family = "\(.*\)"/\1/g' <"$CONFIGURATIONS"/ghostty/config.local)

FONTS_AVAILABLE=("BQN386 Unicode" "Departure Mono" "Comic Mono" "Iosevka Term SS07" "Miracode" "mononoki")

switch_alacritty() {
    (
        ALACRITTY_CONFIGURATION="$CONFIGURATIONS/alacritty/local.toml"

        if [ ! -f "$ALACRITTY_CONFIGURATION" ]; then
            echo "[font.normal]" >"$ALACRITTY_CONFIGURATION"
            echo "family = '$FONT'" >>"$ALACRITTY_CONFIGURATION"
        else
            sed -i "s|^\([[:space:]]*\)family = .*|\1family = '$FONT'|" "$ALACRITTY_CONFIGURATION"
        fi

        touch "$CONFIGURATIONS/alacritty/alacritty.toml"
    )
}

switch_ghostty() {
    (
        GHOSTTY_CONFIGURATION="$CONFIGURATIONS/ghostty/config.local"

        if [ ! -f "$GHOSTTY_CONFIGURATION" ]; then
            echo "font-family = \"$FONT\"" >"$GHOSTTY_CONFIGURATION"
        else
            sed -i "s|^font-family = .*|font-family = \"$FONT\"|" "$GHOSTTY_CONFIGURATION"
        fi

        kill -USR2 "$(pgrep ghostty)"
    )
}

usage() {
    (
        echo "Usage: $(basename "$0") <font_name>"
        echo -n "Available fonts: "
        for font in "${FONTS_AVAILABLE[@]}"; do
            if [ "$font" = "$FONT_IN_USE" ]; then
                printf "\033[4m%s\033[0m" "$font"
            else
                echo -n "$font"
            fi
            if [ "$font" != "${FONTS_AVAILABLE[-1]}" ]; then
                echo -n ", "
            fi
        done
        echo
    )
}

main() {
    if [ $# -ne 1 ]; then
        usage "$@"
        exit 0
    fi

    FONT="$1"

    VALID=false

    for avail in "${FONTS_AVAILABLE[@]}"; do
        if [ "$FONT" = "$avail" ]; then
            VALID=true
            break
        fi
    done

    if [ "$VALID" = false ]; then
        usage "$@"
        exit 1
    fi

    if [ "$FONT" = "$FONT_IN_USE" ]; then
        echo "I can't handle change O.o"
        exit 0
    fi

    switch_alacritty
    switch_ghostty

    printf "Switched to \033[4m%s\033[0m\n" "$FONT"
}

main "$@"
