#!/usr/bin/env bash

# A _better_ way to view system information...

time=$(date "+%H:%M")
date=$(date "+%a %B %d")

terminal_font=$(awk '/font-family/ {sub("font-family = ",""); print; exit}' ~/.config/ghostty/config)

uptime=$(uptime --pretty | sed -r 's/up //; s/ days?,/d/; s/ hours?,/h/; s/ minutes?/m/')

ram_info=$(free -h)
ram_used=$(echo "$ram_info" | awk '/Mem/ {gsub("G",""); print $3}')
ram_total=$(echo "$ram_info" | awk '/Mem/ {sub("G",""); print $2}')
ram_percent=$(echo "$ram_info" | awk '/Mem/ {printf("%d", $3/$2 * 100)}')
ram_info="$ram_used / $ram_total GiB (${ram_percent}%)"

home_info=$(df -h -T /home | tail -n 1)
home_used=$(echo "$home_info" | awk '{gsub("G",""); print $4}')
home_total=$(echo "$home_info" | awk '{sub("G",""); print $3}')
home_percent=$(echo "$home_info" | awk '{print $6}')
home_type=$(echo "$home_info" | awk '{print $2}')
home_info="$home_used / $home_total GiB ($home_percent) ($home_type)"

root_info=$(df -h -T / | tail -n 1)
root_used=$(echo "$root_info" | awk '{gsub("G",""); print $4}')
root_total=$(echo "$root_info" | awk '{sub("G",""); print $3}')
root_percent=$(echo "$root_info" | awk '{print $6}')
root_type=$(echo "$root_info" | awk '{print $2}')
root_info="$root_used / $root_total GiB ($root_percent) ($root_type)"

albums=$(mpc stats | awk '/Albums/ {print $2}')

resolution=$(xrandr | awk -F ", " '{sub("current ", ""); gsub(" x ","x"); print $2; exit}')

if [[ -f /tmp/product_name ]]; then
  computer_name=$(</tmp/product_name)
else
  computer_name=$(sudo dmidecode -s system-version)
  echo "$computer_name" >/tmp/product_name
fi

cpu_info=$(awk -F ": " '/model name/ {gsub(/\(TM\)|\(R\)/, ""); print $2; exit}' /proc/cpuinfo)

kernel=$(uname -srm)

shell=$(basename "$SHELL")

wm=$(xprop -id "$(xprop -root _NET_SUPPORTING_WM_CHECK | awk '{print $NF}')" _NET_WM_NAME | awk -F "\"" '{print $2}' | head -n 1)

distro=$(awk '/^NAME=/ {sub("NAME=", ""); gsub(/"/,""); print}' /etc/os-release)

package_count=0
if [[ $distro == NixOS ]]; then
  package_count=$(find /nix/store/ -mindepth 1 -maxdepth 1 -type d -not -name "\.*" | wc -l)
elif [[ $distro == "Arch Linux" ]]; then
  package_count=$(pacman -Qqe | wc -l)
fi

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

disk_info_raw=$(df --human-readable --output=size,used,pcent / | tail -n 1)
disk_total=$(echo "$disk_info_raw" | awk '{print $1}')
disk_used=$(echo "$disk_info_raw" | awk '{print $2}')
disk_percent=$(echo "$disk_info_raw" | awk '{print $3}')
disk_info="$disk_used / $disk_total GiB ($disk_percent)"

clear -x

cat <<EOF
$bld
$f7                 .c0N.   .'c.
$f7      'Okdl:'  ;OMMMMKOKNMMW:;o0l  .'.     $H the$f1 cat
$f7      ;MMMMMMWWMMMMMMMMMMMMMMMMMXKWMMK
$f7      'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK     $H $f4$time$NC - $f7$date
$f7       NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO     $f6 $USER $f7@ $f1$HOSTNAME
$f7       dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:
$f7       'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.      Editor     »$f4 $EDITOR
$f7       'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM;      Term Font  »$f4 $terminal_font$NC
$f7       lMMMMM  MMMMMMMMMM  MMMMMMMMMM,      Uptime     »$f4 $uptime
$f7       KMMMMM  MMMMMMMMMM  MMMMMMMMMM.      RAM        »$f4 $ram_info
$f7      ;WMMMMMkNMMMMMMMMMMONMMMMMMMMMW:      DISK       »$f4 $disk_info
$f7    oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO     Packages   »$f4 $package_count
$f7   .,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMXdxo    Albums     »$f4 $albums
$f7      ;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM:      Resolution »$f4 $resolution
$f7     .::,  .;ok0NMMMMWNK0kdoc;'  'cxK0
$f1                .:cc:;;.                    Computer »$f4 $computer_name
$f1                .o0MMMK'                    CPU      »$f4 $cpu_info
$f1                  xMMM:                     Kernel   »$f4 $kernel
$f1                  KMMMl                     Shell    »$f4 $shell
$f1                 .MMMMo                     WM       »$f4 $wm
$f1                 ,MMMMx                     @        »$f4 $distro
$f1                 oMMMMx
$f1                 OMMMMO                     $f7"Hacks and glory await!"
$f1                 .OMMMd                                    $f7- the$f1 cat
$f1                   :Nl

EOF

# vim:sw=2:ts=2:et:
