#!/usr/bin/env bash

main() {
	local selected

	selected=$(
		tmux list-sessions -F '#S' |
			fzf --no-preview --ansi --color hl:reverse:-1,hl+:reverse:-1 \
				--prompt '  Sessions :: ' \
				--tmux center,border-native
	)

	if [[ -z $selected ]]; then
		exit 0
	fi

	local tmux_running=$(pgrep tmux)

	if [[ -z $TMUX ]]; then
		tmux attach -t $selected 2>/dev/null
	else
		tmux switch-client -t $selected 2>/dev/null
	fi
}

main "$@"
