#!/usr/bin/env bash

# Sets the image as a wallpaper for desktop

WALLPAPERS_DIR="$HOME/.local/share/wallpapers"

if [[ $1 == "--help" || $1 == "-h" ]]; then
  echo "Usage: wallpaper [image.png]"
  echo "Sets the specified PNG as wallpaper. If no argument, selects randomly."
  exit 0
fi

if [[ -z $1 ]]; then
  # Random selection
  files=("$WALLPAPERS_DIR"/*.png)
  if [[ ${#files[@]} -gt 0 ]]; then
    wallpaper="${files[RANDOM % ${#files[@]}]}"
  fi
elif [[ $1 != /* ]]; then
  wallpaper="$WALLPAPERS_DIR/$1"
else
  wallpaper="$1"
fi

# Fallback to default if not set or doesn't exist
if [[ -z $wallpaper || ! -f "$wallpaper" ]]; then
  wallpaper="$WALLPAPERS_DIR/default.png"
fi

ln -sf "$wallpaper" "$WALLPAPERS_DIR/default.png" &
feh --bg-fill "$wallpaper" &

# vim:ft=sh:sw=2:ts=2:et:
