#!/usr/bin/env bash

# set -x # WARN: Only for debugging...
set -euo pipefail

main() {
  if [[ ! $# -gt 1 ]]; then
    echo 'O.o'
    return 1
  fi

  case "$1" in
    -c | --check)
      PID=$(lsof -i -P -n | grep LISTEN | grep "$2" | awk '{print $2}')
      [[ ! -z "$PID" ]] && ps "$PID" || return 0
      ;;
    -k | --kill)
      wtf --check "$2" | xargs kill -9
      ;;
    -h | --help)
      usage
      return 0
      ;;
    *) ;;
  esac
}

main "$@"
