[colors.primary]
background = "#FAF4ED"
foreground = "#404553"

[colors.cursor]
cursor     = "#385372"

[colors.normal]
black      = "#FAF4ED"
blue       = "#97C0DC"
cyan       = "#3B8F84"
green      = "#5F8C3F"
magenta    = "#6666A8"
red        = "#C84B2B"
white      = "#385372"
yellow     = "#C88500"

[colors.bright]
black      = "#385372"
blue       = "#97C0DC"
cyan       = "#3B8F84"
green      = "#5F8C3F"
magenta    = "#6666A8"
red        = "#C84B2B"
white      = "#6666A8"
yellow     = "#C88500"
