[colors.primary]
background = "#2F353E"
foreground = "#BEBEC3"

[colors.cursor]
cursor     = "#FFFFFF"

[colors.normal]
black      = "#2F353E"
blue       = "#708296"
cyan       = "#79ADA7"
green      = "#A4BD84"
magenta    = "#CAAFEB"
red        = "#E87C69"
white      = "#E5E5EB"
yellow     = "#E6BB86"

[colors.bright]
black      = "#E5E5EB"
blue       = "#708296"
cyan       = "#79ADA7"
green      = "#A4BD84"
magenta    = "#CAAFEB"
red        = "#E87C69"
white      = "#8F9FBC"
yellow     = "#E6BB86"
