[colors.primary]
background = "#2D353B"
foreground = "#D8CAAC"

[colors.cursor]
cursor     = "#D8CAAC"

[colors.normal]
black      = "#3C474D"
blue       = "#83B6AF"
cyan       = "#87C095"
green      = "#A7C080"
magenta    = "#D39BB6"
red        = "#E68183"
white      = "#868D80"
yellow     = "#D9BB80"

[colors.bright]
black      = "#868D80"
blue       = "#83B6AF"
cyan       = "#87C095"
green      = "#A7C080"
magenta    = "#D39BB6"
red        = "#E68183"
white      = "#868D80"
yellow     = "#D9BB80"
