[colors.primary]
background = "#282828"
foreground = "#D4BE98"

[colors.normal]
black      = "#6C645E"
blue       = "#7DAEA3"
cyan       = "#89B482"
green      = "#A9B665"
magenta    = "#D3869B"
red        = "#EA6962"
white      = "#D4BE98"
yellow     = "#D8A657"

[colors.bright]
black      = "#6C645E"
blue       = "#7DAEA3"
cyan       = "#89B482"
green      = "#A9B665"
magenta    = "#D3869B"
red        = "#EA6962"
white      = "#D4BE98"
yellow     = "#D8A657"
