[colors.primary]
background = "#E7E7E7"
foreground = "#1B1B1B"

[colors.cursor]
cursor     = "#1B1B1B"
text       = "#E7E7E7"

[colors.normal]
black      = "#E7E7E7"
blue       = "#537788"
cyan       = "#586E62"
green      = "#6A824F"
magenta    = "#938AA9"
red        = "#B23B34"
white      = "#1B1B1B"
yellow     = "#A0713C"

[colors.bright]
black      = "#D8D8D8"
blue       = "#7FB4CA"
cyan       = "#7AA89F"
green      = "#87A987"
magenta    = "#B1B1D2"
red        = "#E46876"
white      = "#A0A0A0"
yellow     = "#DEBE97"
