[colors.primary]
background = "#FFFFFF"
foreground = "#404553"

[colors.cursor]
cursor     = "#385372"

[colors.normal]
black      = "#FFFFFF"
blue       = "#BEC8CC"
cyan       = "#673AB7"
green      = "#608C88"
magenta    = "#000000"
red        = "#E0B153"
white      = "#9FADB4"
yellow     = "#F09276"

[colors.bright]
black      = "#9FADB4"
blue       = "#9FADB4"
cyan       = "#673AB7"
green      = "#608C88"
magenta    = "#000000"
red        = "#E0B153"
white      = "#9FADB4"
yellow     = "#F09276"
