[colors.primary]
background = "#F3F3F3"
foreground = "#181819"

[colors.cursor]
cursor     = "#181819"

[colors.normal]
black      = "#E7E7E7"
blue       = "#77BCD8"
cyan       = "#77BCD8"
green      = "#72AC38"
magenta    = "#A793E3"
red        = "#D44E69"
white      = "#171718"
yellow     = "#BE9B44"

[colors.bright]
black      = "#7E8490"
blue       = "#77BCD8"
cyan       = "#77BCD8"
green      = "#72AC38"
magenta    = "#A793E3"
red        = "#D44E69"
white      = "#171718"
yellow     = "#BE9B44"
