[colors.primary]
background = "#2C2E34"
foreground = "#E2E2E3"

[colors.cursor]
cursor     = "#E2E2E3"

[colors.normal]
black      = "#181819"
blue       = "#76CCE0"
cyan       = "#85D3F2"
green      = "#9ED072"
magenta    = "#B39DF3"
red        = "#FC5D7C"
white      = "#E2E2E3"
yellow     = "#E7C664"

[colors.bright]
black      = "#7F8490"
blue       = "#76CCE0"
cyan       = "#85D3F2"
green      = "#9ED072"
magenta    = "#B39DF3"
red        = "#FC5D7C"
white      = "#E2E2E3"
yellow     = "#E7C664"
