[general]
import = [
  "~/.config/alacritty/themes/macro-dark.toml",
  "~/.config/alacritty/themes/dark.toml",
  "~/.config/alacritty/theme.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/themes/macro-dark.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/themes/dark.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/theme.toml",
]
live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "alacritty"

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login", "--interactive"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[font]
size = 12

[font.normal]
family = "scientifica"

[font.offset]
x = 0 
y = 0

[window]
opacity = 1
decorations = "none"

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Escape"
mods = "Control"
action = "ToggleViMode"  

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ToggleViMode"  
