#!/usr/bin/env bash

# set -x # WARN: Only used for debugging...
set -euo pipefail

NOTIFICATION_ID=1001

STATE="${XDG_STATE_HOME:-$HOME/.local/state}/caffeine"

STATUS=$(xset -q 2>/dev/null | sed -n 's/.*DPMS is \(Enabled\|Disabled\).*/\1/p')

main() {
  if [[ -f "$STATE" ]]; then
    STATUS=$(cat "$STATE")
  fi

  if [ "$STATUS" = 'Enabled' ]; then
    xset s off
    xset -dpms
    notify-send -u NORMAL -a 'Caffeine' "Caffeine" "Display can't sleep now" -r "$NOTIFICATION_ID"
    echo "Disabled" >"$STATE"
  else
    xset s on
    xset +dpms
    notify-send -u NORMAL -a 'Caffeine' "Caffeine" "Display can sleep now" -r "$NOTIFICATION_ID"
    echo "Enabled" >"$STATE"
  fi
}

main "$@"

# vim:ft=sh:sw=2:ts=2:et:
