#!/usr/bin/env bash

# set -x # WARN: Only for debugging...
set -euo pipefail

usage()  {
  printf "Usage: %s [OPTIONS] PORT\n" "$(basename "$0")"
  printf "Options:\n"
  printf "  -k, --kill         Send a kill signal to PID on PORT\n"
  printf "  -c, --check        Checks the PID running on PORT\n"
  printf "  -h, --help         Show this help message\n"
}

main() {
  if [[ $# -eq 0 ]]; then
    usage
    return 1
  fi

  case "$1" in
    -c | --check)
      PID=$(lsof -i -P -n | grep LISTEN | grep "$2" | awk '{print $2}')
      [[ ! -z "$PID" ]] && ps "$PID" || return 0
      ;;
    -k | --kill)
      wtf --check "$2" | xargs kill -9
      ;;
    -h | --help)
      usage
      return 0
      ;;
    *) ;;
  esac
}

main "$@"
